# Generated by Django 5.2.15 on 2026-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationalPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "operational permission",
                "verbose_name_plural": "operational permissions",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
