# Generated by Django 5.2.15 on 2026-07-07 15:48

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("manual_adjustment", "Manual adjustment"),
                            ("order_confirmed", "Order confirmed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("previous_stock", models.PositiveIntegerField()),
                ("new_stock", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_delta", 0), _negated=True),
                        name="inventory_movement_quantity_delta_not_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "new_stock",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("previous_stock"),
                                    "+",
                                    models.F("quantity_delta"),
                                ),
                            )
                        ),
                        name="inventory_movement_stock_math_matches_delta",
                    ),
                ],
            },
        ),
    ]
