# Generated by Django 5.2.15 on 2026-08-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("manual_adjustment", "Manual adjustment"),
                    ("order_confirmed", "Order confirmed"),
                    ("order_reserved", "Order reserved"),
                    ("order_cancelled", "Order cancelled"),
                ],
                max_length=40,
            ),
        ),
    ]
