# Generated by Django 5.2.15 on 2026-06-30 18:33

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delta", 0), _negated=True),
                name="inventory_movement_quantity_delta_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "new_stock",
                        django.db.models.expressions.CombinedExpression(
                            models.F("previous_stock"), "+", models.F("quantity_delta")
                        ),
                    )
                ),
                name="inventory_movement_stock_math_matches_delta",
            ),
        ),
    ]
