export const apiFixtures = {
  authSession: {
    access: "mock-access-token",
    refresh: "mock-refresh-token",
    user: {
      id: 1,
      username: "cliente_demo",
      email: "cliente@example.com",
      first_name: "Cliente",
      last_name: "Demo",
      phone: "5550101",
      state: "Baja California",
      city: "Tijuana",
      role: "cliente",
    },
  },
  product: {
    id: 1,
    name: "Daybed Roble",
    description: "Sofá cama de madera con tapizado claro.",
    price: "1200.00",
    material: "roble",
    color: "natural",
    style: "moderno",
    dimensions: "200 x 90 x 80 cm",
    stock: 5,
    minimum_stock: 2,
    low_stock: false,
    active: true,
    main_image: "",
    category: 1,
    category_detail: {
      id: 1,
      name: "Sofás cama",
      slug: "sofas-cama",
      description: "Muebles convertibles para sala y descanso.",
      active: true,
    },
    images: [],
  },
  paginatedProducts: {
    count: 1,
    next: null,
    previous: null,
    results: [],
  },
  cart: {
    id: 1,
    subtotal: "2400.00",
    items: [
      {
        id: 1,
        quantity: 2,
        line_total: "2400.00",
        product: null,
      },
    ],
  },
  deliveryEstimate: {
    origin_latitude: "32.51490000",
    origin_longitude: "-117.03820000",
    destination_latitude: "32.60000000",
    destination_longitude: "-117.10000000",
    distance_km: "12.500",
    estimated_duration_minutes: "30.0",
    delivery_fee: "180.00",
    delivery_zone: "standard",
    geocoding_provider: "nominatim",
    distance_provider: "openrouteservice",
  },
  order: {
    id: 1,
    status: "pending",
    products_subtotal: "2400.00",
    delivery_fee: "180.00",
    total: "2580.00",
    items: [],
    original_address: "Av. Reforma 123, Tijuana",
    formatted_address: "Av. Reforma 123, Tijuana, Baja California",
    latitude: "32.60000000",
    longitude: "-117.10000000",
    distance_km: "12.500",
    estimated_duration_minutes: "30.0",
    delivery_zone: "standard",
    geocoding_provider: "nominatim",
    distance_provider: "openrouteservice",
    stock_decremented_at: null,
  },
  dashboardMetrics: {
    total_orders: 12,
    total_simulated_sales: "25800.00",
    orders_by_status: [
      { status: "pending", count: 3 },
      { status: "confirmed", count: 4 },
      { status: "preparing", count: 2 },
      { status: "shipped", count: 1 },
      { status: "delivered", count: 2 },
      { status: "cancelled", count: 0 },
    ],
    low_stock_count: 2,
    recent_orders: [],
    average_delivery_fee: "180.00",
    average_delivery_distance: "12.500",
  },
};

apiFixtures.paginatedProducts.results = [apiFixtures.product];
apiFixtures.cart.items[0].product = apiFixtures.product;
apiFixtures.order.items = [
  {
    id: 1,
    product: apiFixtures.product.id,
    product_name: apiFixtures.product.name,
    unit_price: apiFixtures.product.price,
    quantity: 2,
    line_total: "2400.00",
  },
];
