# Generated by Django 5.2.15 on 2026-07-16 03:21

from django.db import migrations, models


def backfill_order_item_snapshots(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.select_related("product").order_by("id"):
        product = item.product
        item.product_sku = product.sku or ""
        item.product_snapshot = {
            "sku": product.sku,
            "name": product.name,
            "material": product.material,
            "color": product.color,
            "style": product.style,
            "structured_dimensions": {
                "width_cm": (
                    str(product.width_cm) if product.width_cm is not None else None
                ),
                "height_cm": (
                    str(product.height_cm) if product.height_cm is not None else None
                ),
                "depth_cm": (
                    str(product.depth_cm) if product.depth_cm is not None else None
                ),
                "length_cm": (
                    str(product.length_cm) if product.length_cm is not None else None
                ),
                "diameter_cm": (
                    str(product.diameter_cm)
                    if product.diameter_cm is not None
                    else None
                ),
                "weight_kg": (
                    str(product.weight_kg) if product.weight_kg is not None else None
                ),
            },
            "specifications": product.specifications,
        }
        item.save(update_fields=("product_sku", "product_snapshot"))


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_category_specification_schema_product_depth_cm_and_more",
        ),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            backfill_order_item_snapshots,
            migrations.RunPython.noop,
        ),
    ]
