# Generated by Django 5.2.15 on 2026-08-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_product_sku_orderitem_product_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Tarjeta"),
                    ("transfer", "Transferencia"),
                    ("cash", "Efectivo contra entrega"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("authorized", "Autorizado"),
                    ("awaiting_transfer", "Pendiente de transferencia"),
                    ("pay_on_delivery", "Pago contra entrega"),
                    ("failed", "Fallido"),
                ],
                default="pay_on_delivery",
                max_length=30,
            ),
        ),
    ]
