# Generated by Codex on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_integrity_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_duration_minutes",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
            ),
        ),
    ]
