# Generated by Django 5.2.15 on 2026-07-16 03:21

from django.db import migrations, models


def backfill_product_skus(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.filter(sku__isnull=True).order_by("id"):
        product.sku = f"DAY-{product.id:05d}"
        product.save(update_fields=("sku",))


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="specification_schema",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="depth_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="diameter_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.RunPython(backfill_product_skus, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["active", "category"], name="catalog_pro_active_99b750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="catalog_pro_price_2d2a4c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["width_cm"], name="catalog_pro_width_c_427ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["height_cm"], name="catalog_pro_height__7f2c5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["depth_cm"], name="catalog_pro_depth_c_4888e1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width_cm__gte", 0), ("width_cm__isnull", True), _connector="OR"
                ),
                name="product_width_cm_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height_cm__gte", 0), ("height_cm__isnull", True), _connector="OR"
                ),
                name="product_height_cm_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("depth_cm__gte", 0), ("depth_cm__isnull", True), _connector="OR"
                ),
                name="product_depth_cm_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("length_cm__gte", 0), ("length_cm__isnull", True), _connector="OR"
                ),
                name="product_length_cm_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("diameter_cm__gte", 0),
                    ("diameter_cm__isnull", True),
                    _connector="OR",
                ),
                name="product_diameter_cm_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_kg__gte", 0), ("weight_kg__isnull", True), _connector="OR"
                ),
                name="product_weight_kg_non_negative",
            ),
        ),
    ]
