# Generated by Django 5.2.15 on 2026-07-16 03:35

from django.db import migrations


def preserve_legacy_dimensions_text(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.exclude(dimensions="").order_by("id"):
        specifications = dict(product.specifications or {})
        specifications.setdefault("_legacy_dimensions_text", product.dimensions)
        product.specifications = specifications
        product.save(update_fields=("specifications",))


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_specification_schema_product_depth_cm_and_more"),
    ]

    operations = [
        migrations.RunPython(
            preserve_legacy_dimensions_text,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
    ]
