# Generated by Django 5.2.15 on 2026-08-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_merchandising_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_feature_5c18a9_idx",
            old_name="catalog_pro_feature_d38956_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_room_eefb4d_idx",
            old_name="catalog_pro_room_aaf7dd_idx",
        ),
    ]
